<a href="https://colab.research.google.com/github/mostafa-asefy/neural-networks-from-zero/blob/main/Artificial_Neural_Networks_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neural Network Class Definition

In [3]:
import numpy as np
from scipy.special import expit


class NeuralNetwork:

    # راه اندازی شبکه عصبی 
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # تعیین تعداد نورون‌های لایه‌های مختلف
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        # تعیین نرخ یادگیری
        self.learning_rate = learning_rate
        
        # ایجاد تابع فعال سازی که اینجا سیگموییدی است ولی می تواند متفاوت باشد
        self.activation_function = lambda x : expit(x)

        # ایجاد دو ماتریس وزن‌های اولیه
        # یکی برای وزن‌های بین لایه ورودی و مخفی و یکی برای وزن‌های بین لایه مخفی و خروجی 
        # هر وزن با ایندکس آی و جی، وزن اتصال بین نورون آی از لایه مبدا به نورون جی در لایه مقصد است.
        #  و به همین ترتیب w12 w21 مثلا
        self.w_i_h = np.random.default_rng().normal(0, pow(self.input_nodes, -0.5),
                                                    (self.hidden_nodes, self.input_nodes))
        self.w_h_o = np.random.default_rng().normal(0, pow(self.hidden_nodes, -0.5),
                                                    (self.output_nodes, self.hidden_nodes))
        pass


    # محاسبه خروجی شبکه با دادن ورودی - پیش خور
    def query(self, input_list):
        # تبدیل لیست مقادیر ورودی به آرایه دوبعدی
        inputs = np.array(input_list, ndmin=2).T

        # محاسبه سیگنال ورودی و سپس خروجی لایه مخفی
        x_hidden = np.dot(self.w_i_h, inputs)
        o_hidden = self.activation_function(x_hidden)

        # محاسبه سیگنال ورودی و سپس خروجی لایه خروجی
        x_output = np.dot(self.w_h_o, o_hidden)
        o_output = self.activation_function(x_output)

        return o_output


    # یادگیری شبکه بر اساس یک نمونه ورودی/خروجی - پس انتشار
    def train(self, input_list, targets_list):
        # محاسبه سیگنال‌های ورودی و خروجی لایه‌ها
        inputs = np.array(input_list, ndmin=2).T

        x_hidden = np.dot(self.w_i_h, inputs)
        o_hidden = self.activation_function(x_hidden)

        x_output = np.dot(self.w_h_o, o_hidden)
        o_output = self.activation_function(x_output)

        #محاسبه خطای شبکه بر اساس اختلاف خروجی با هدف‌ها
        targets = np.array(targets_list, ndmin=2).T
        output_errors = targets - o_output
        #پس انتشار خطای شبکه روی نورون‌های لایه مخفی
        hidden_errors = np.dot(self.w_h_o.T, output_errors)

        # محاسبه وزن‌های جدید اتصال‌ها با گرادیان کاهشی
        self.w_h_o += self.learning_rate * np.dot((output_errors * o_output * (1-o_output)), o_hidden.T)
        self.w_i_h += self.learning_rate * np.dot((hidden_errors * o_hidden * (1-o_hidden)), inputs.T)
        
        


# Neural Network Instance Creation

In [2]:
nn = NeuralNetwork(3, 3, 3, 0.3)
print(nn.w_i_h)
nn.query([1, 2, 3])

[[ 1.32209206  0.53833378  0.28324113]
 [-0.31112643 -0.2339579  -0.05781636]
 [ 0.70696668 -0.85359874 -0.66391693]]


array([[0.60728818],
       [0.53034918],
       [0.49900366]])