<a href="https://colab.research.google.com/github/mostafa-asefy/neural-networks-from-zero/blob/main/Artificial_Neural_Networks_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neural Network Class Definition

In [8]:
import numpy as np
from scipy.special import expit


class NeuralNetwork:

    # initialize the neural network 
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # set number of nodes in input, hidden and output layers
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        # set the learning rate
        self.learning_rate = learning_rate

        self.activation_function = lambda x : expit(x)

        # link weight matrices, w_input_hidden and w_hidden_output
        # weights inside the arrays are w_i_j, where link is from node 
        # i to node j in the next layer
        # w11 w21
        # w12 w22 etc
        # self.w_i_h = np.random.rand(self.hidden_nodes, self.input_nodes) - 0.5
        self.w_i_h = np.random.default_rng().normal(0, pow(self.input_nodes, -0.5),
                                                    (self.hidden_nodes, self.input_nodes))
        # self.w_h_o = np.random.rand(self.output_nodes, self.hidden_nodes) - 0.5
        self.w_h_o = np.random.default_rng().normal(0, pow(self.hidden_nodes, -0.5),
                                                    (self.output_nodes, self.hidden_nodes))
        pass

    # train the neural network
    def train():
        pass

    # query the neural network
    def query(self, input_list):
        inputs = np.array(input_list, ndmin=2).T

        x_hidden = np.dot(self.w_i_h, inputs)
        o_hidden = self.activation_function(x_hidden) 

        x_output = np.dot(self.w_h_o, o_hidden)
        o_output = self.activation_function(x_output)

        return o_output


# Neural Network Instance Creation

In [10]:
nn = NeuralNetwork(3, 3, 3, 0.3)
print(nn.w_i_h)
nn.query([1, 2, 3])

[[-0.01403313 -0.22704182 -0.80838127]
 [-0.33207051  0.71597451  0.75153626]
 [-0.94717473  0.26076063  0.18716868]]


array([[0.5867502 ],
       [0.23209043],
       [0.58561182]])